### ISSUE TITLE
Logout link gives Forbidden (403)

### ISSUE THREAD

**Issue by ghost** [micronaut-guides/micronaut-oauth2-oidc-google#1]
In the current oauth2 example, the logout link provided after successful login gives forbidden 403 status

**Comment by roman-klauser** [comment]
@ashishkumarthoughtworks same here. Did you solve this issue?

**Comment by CVN-65** [comment]
Tried with micronautVersion=1.2.5 but have same effect

**Comment by ilopmar** [comment]
There was an error with the indentation of `application.yml` and now it's working.
