### ISSUE TITLE
thymeleaf build error

### ISSUE THREAD

**Issue by davRg** [micronaut-guides/micronaut-oauth2-oidc-google#5]
There is a problem when you try to build the example with **micronaut-views-thymeleaf** version

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find io.micronaut:micronaut-views-thymeleaf:.
     Required by:
         project :

I solved that issue adding a version to that library.
(sorry by my english)

**Comment by sdelamo** [comment]
In Micronaut 2.0 the dependency group has been changed. 

`    implementation("io.micronaut.views:micronaut-views-thymeleaf")` is the only thing you will need. It will bring the necessary transitive dependencies
